run_migrations: true
network_id: &network_id "Undeployed"

chain_indexer_application:
  network_id: *network_id
  blocks_buffer: 10
  save_zswap_state_after: 1000
  caught_up_max_distance: 10
  caught_up_leeway: 5

wallet_indexer_application:
  network_id: *network_id
  active_wallets_repeat_delay: "100ms"
  active_wallets_ttl: "30m"
  transaction_batch_size: 10

infra:
  node:
    url: "ws://localhost:9944"
    reconnect_max_delay: "10s"
    reconnect_max_attempts: 30

  storage:
    cnn_url: "/data/indexer.sqlite"

  api:
    address: "0.0.0.0"
    port: 8088
    request_body_limit: "1MiB"
    max_complexity: 200
    max_depth: 15
    network_id: *network_id

telemetry:
  tracing:
    enabled: false
    service_name: "indexer"
    otlp_exporter_endpoint: "http://localhost:4317"
  metrics:
    enabled: false
    address: "0.0.0.0"
    port: 9000