{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "midnight-services.namespace" . }}
  labels:
    {{- include "midnight-services.labels" . | nindent 4 }}
{{- end }}
